import { useEffect, useMemo, useState } from "react";
import { api, setAuthToken } from "./api";

const card={background:"#fff",border:"1px solid #dce9e3",borderRadius:18,padding:20,boxShadow:"0 8px 28px rgba(13,57,45,.06)"};
const input={width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #d4e4dd",borderRadius:10};
const btn={border:0,borderRadius:10,padding:"11px 15px",fontWeight:800,cursor:"pointer"};
const money=n=>`₦${Number(n||0).toLocaleString()}`;

function AdminLogin({onAuthenticated}){
 const resetToken=useMemo(()=>new URLSearchParams(location.search).get("reset")||"",[]);
 const [mode,setMode]=useState(resetToken?"reset":"login"),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{if(mode==="login"){const d=await api.adminLogin({username,password});localStorage.setItem("cv_admin_token_v2",d.token);setAuthToken(d.token);onAuthenticated(d.token,d.user)}else if(mode==="forgot"){setMessage((await api.adminForgotPassword(username)).message)}else{if(password.length<12)throw Error("Use at least 12 characters.");if(password!==confirm)throw Error("Passwords do not match.");setMessage((await api.adminResetPassword(resetToken,password)).message);history.replaceState({},"","/admin");setMode("login");setPassword("");setConfirm("")}}catch(x){setError(x.message)}finally{setBusy(false)}};
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"linear-gradient(135deg,#f1faf6,#e7f5ef 55%,#fff)"}}><section style={{...card,width:"100%",maxWidth:440,padding:34}}><h1 style={{marginTop:0}}>CampusVerse Admin</h1><p style={{color:"#637a71"}}>Secure administrator control center.</p><form onSubmit={submit} style={{display:"grid",gap:12}}>{mode!=="reset"&&<input style={input} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Admin username or email" autoComplete="username" required/>}{mode!=="forgot"&&<input style={input} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==="reset"?"New password":"Password"} type="password" minLength={mode==="reset"?12:1} required/>}{mode==="reset"&&<input style={input} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password" type="password" minLength={12} required/>}{error&&<div style={{color:"#b42318"}}>{error}</div>}{message&&<div style={{color:"#087f5b"}}>{message}</div>}<button disabled={busy} style={{...btn,background:"#087f5b",color:"#fff"}}>{busy?"Please wait…":mode==="login"?"Sign in securely":mode==="forgot"?"Send reset link":"Update password"}</button></form>{mode==="login"&&<button onClick={()=>setMode("forgot")} style={{marginTop:15,border:0,background:"transparent",color:"#087f5b",fontWeight:800}}>Forgot password?</button>}{mode==="forgot"&&<button onClick={()=>setMode("login")} style={{marginTop:15,border:0,background:"transparent",color:"#087f5b",fontWeight:800}}>Back to sign in</button>}<small style={{display:"block",marginTop:20,color:"#7b8e87"}}>8-hour admin JWT • server-side ADMIN role check</small></section></main>;
}

export default function AdminPortal(){
 const [token,setToken]=useState(()=>localStorage.getItem("cv_admin_token_v2")),[user,setUser]=useState(null),[tab,setTab]=useState("overview"),[overview,setOverview]=useState(null),[refs,setRefs]=useState([]),[images,setImages]=useState([]),[products,setProducts]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [conversion,setConversion]=useState({referralId:"",sourceType:"SERVICE",sourceId:"",baseAmount:"",note:""});
 const [product,setProduct]=useState({title:"",description:"",price:"",category:"Gadgets",conditionType:"NEW",condition:"New",location:"UNN Main Campus",images:[],stock:1});
 const toast=x=>{setMessage(x);clearTimeout(window.cvToast);window.cvToast=setTimeout(()=>setMessage(""),3500)};
 const logout=()=>{localStorage.removeItem("cv_admin_token_v2");setAuthToken(null);setToken(null);setUser(null)};
 const auth=(t,u)=>{localStorage.setItem("cv_admin_token_v2",t);setAuthToken(t);setToken(t);setUser(u)};
 const load=async()=>{if(!token)return;setBusy(true);try{setAuthToken(token);const [o,r,i,p]=await Promise.all([api.getAdminOverviewV2(),api.getAdminReferrals(),api.getAdminImages(),api.getAdminProductsV2()]);setOverview(o);setRefs(r);setImages(i);setProducts(p)}catch(e){if(/session|expired|authorization|admin access|invalid/i.test(e.message))logout();else toast(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(!token)return;setAuthToken(token);api.adminMe().then(setUser).then(load).catch(logout)},[token]);
 const upload=async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/"))return toast("Only image files are allowed.");if(f.size>8*1024*1024)return toast("Image must be 8MB or smaller.");setBusy(true);try{const r=await api.uploadAdminImage(f);setImages(x=>[r,...x]);setProduct(x=>({...x,images:[...x.images,r.url]}));toast("Image uploaded successfully")}catch(x){toast(x.message)}finally{setBusy(false);e.target.value=""}};
 const publish=async()=>{if(!product.title.trim()||!product.price||!product.images.length)return toast("Add title, price and at least one image.");setBusy(true);try{await api.createProduct(product);toast("Product published");setProduct({title:"",description:"",price:"",category:"Gadgets",conditionType:"NEW",condition:"New",location:"UNN Main Campus",images:[],stock:1});await load()}catch(e){toast(e.message)}finally{setBusy(false)}};
 const recordConversion=async()=>{if(!conversion.referralId||!conversion.baseAmount)return toast("Select a referral and enter order value.");setBusy(true);try{await api.addReferralConversion(conversion);toast("20% commission recorded");setConversion({referralId:"",sourceType:"SERVICE",sourceId:"",baseAmount:"",note:""});await load()}catch(e){toast(e.message)}finally{setBusy(false)}};
 if(!token||!user)return <AdminLogin onAuthenticated={auth}/>;
 const nav=[["overview","Overview"],["products","Products"],["images","Image Library"],["referrals","Referrals"],["conversion","Record Conversion"]];
 return <div style={{minHeight:"100vh",background:"#f4f8f6",color:"#10201b",fontFamily:"Inter,system-ui,sans-serif"}}>{message&&<div style={{position:"fixed",right:18,top:18,zIndex:100,background:"#063f31",color:"#fff",padding:"12px 16px",borderRadius:12}}>{message}</div>}<header style={{background:"#063f31",color:"#fff",padding:"18px 5vw",display:"flex",justifyContent:"space-between",gap:15,alignItems:"center"}}><div><b style={{fontSize:21}}>CampusVerse Admin</b><div style={{color:"#9ed5c4",fontSize:11}}>Vercel backend • No Railway dependency</div></div><div>{user.username||user.email} • ADMIN <button onClick={logout} style={{...btn,marginLeft:10,background:"#61e7b5",color:"#063f31"}}>Sign out</button></div></header><main style={{maxWidth:1250,margin:"0 auto",padding:"28px 5vw 70px"}}><nav style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:20}}>{nav.map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{...btn,background:tab===k?"#07966c":"#fff",color:tab===k?"#fff":"#34584d",border:"1px solid #d6e5df"}}>{l}</button>)}</nav>{busy&&<div style={{color:"#087f5b",fontSize:13,marginBottom:12}}>Syncing secure admin data…</div>}
 {tab==="overview"&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14}}>{[["Users",overview?.users,"👥"],["Products",overview?.products,"📦"],["Referrals",overview?.referrals,"🔗"],["Commission value",money(overview?.commissions),"💰"],["Pending payouts",overview?.pendingCommissions,"⏳"]].map(([a,b,c])=><div key={a} style={card}><div>{c}</div><span style={{fontSize:12,color:"#6c827b"}}>{a}</span><strong style={{display:"block",fontSize:27}}>{b??"—"}</strong></div>)}</div><div style={{...card,marginTop:18}}><h2>New administrator control center</h2><p style={{color:"#60766e",lineHeight:1.7}}>The previous admin configuration has been replaced. Admin authentication is isolated from student authentication, every protected request re-checks the ADMIN role, item images use Supabase Storage, and referral commissions are created only after administrator confirmation.</p></div></>}
 {tab==="products"&&<div style={card}><h2>Publish marketplace item</h2>{[["title","Item title"],["description","Description"],["price","Price (₦)"],["category","Category"],["condition","Condition"],["location","Location"]].map(([k,p])=><input key={k} style={{...input,marginBottom:10}} placeholder={p} value={product[k]} onChange={e=>setProduct({...product,[k]:e.target.value})}/>)}<label style={{...btn,display:"inline-block",background:"#e5f6ef",color:"#075d46"}}>📷 Upload item image<input type="file" accept="image/*" hidden onChange={upload}/></label><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:14}}>{product.images.map(u=><img key={u} src={u} alt="item" style={{width:95,height:95,objectFit:"cover",borderRadius:10}}/>)}</div><button disabled={busy} onClick={publish} style={{...btn,background:"#07966c",color:"#fff",marginTop:18}}>Publish item</button><h3>Current listings</h3>{products.slice(0,12).map(p=><div key={p.id} style={{display:"flex",gap:10,padding:"10px 0",borderBottom:"1px solid #eef4f1"}}><img src={p.images?.[0]||""} alt="" style={{width:54,height:54,objectFit:"cover",borderRadius:8}}/><div><b>{p.title}</b><div style={{fontSize:12,color:"#6c827b"}}>{money(p.price)} • {p.seller?.name||"Admin"}</div></div></div>)}</div>}
 {tab==="images"&&<div style={card}><h2>Item Image Library</h2><p style={{color:"#6c827b"}}>Upload product photographs here. They are stored outside the frontend bundle in Supabase Storage.</p><label style={{...btn,display:"inline-block",background:"#07966c",color:"#fff"}}>Upload image<input type="file" accept="image/*" hidden onChange={upload}/></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(150px,1fr))",gap:14,marginTop:20}}>{images.map(x=><div key={x.id} style={{border:"1px solid #e0ebe6",borderRadius:12,padding:8}}><img src={x.url} alt={x.fileName||x.file_name||"CampusVerse item"} style={{width:"100%",height:130,objectFit:"cover",borderRadius:8}}/><small>{x.fileName||x.file_name}</small></div>)}</div></div>}
 {tab==="referrals"&&<div style={card}><h2>Referral management</h2><p style={{color:"#6c827b"}}>Current qualifying commission rate: <b>20%</b>. Partners cannot self-declare commissions.</p><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Partner","Customer","Code","Status","Commission","Date"].map(x=><th key={x} style={{textAlign:"left",padding:10,borderBottom:"1px solid #e4eee9"}}>{x}</th>)}</tr></thead><tbody>{refs.map(r=><tr key={r.id}><td style={{padding:10}}><b>{r.referrer_name}</b><small style={{display:"block"}}>{r.referrer_email}</small></td><td>{r.referred_name}</td><td>{r.code}</td><td>{r.status}</td><td>{money(r.commission_total)}</td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>}
 {tab==="conversion"&&<div style={card}><h2>Record qualifying conversion</h2><p style={{color:"#6c827b"}}>Admin confirms the order value; the system calculates 20% automatically.</p><select value={conversion.referralId} onChange={e=>setConversion({...conversion,referralId:e.target.value})} style={{...input,marginBottom:10}}><option value="">Select referral</option>{refs.map(r=><option key={r.id} value={r.id}>{r.referrer_name} → {r.referred_name} ({r.code})</option>)}</select><select value={conversion.sourceType} onChange={e=>setConversion({...conversion,sourceType:e.target.value})} style={{...input,marginBottom:10}}><option>SERVICE</option><option>PRODUCT</option><option>PRINTING</option><option>OTHER</option></select><input style={{...input,marginBottom:10}} placeholder="Order/reference ID" value={conversion.sourceId} onChange={e=>setConversion({...conversion,sourceId:e.target.value})}/><input style={{...input,marginBottom:10}} type="number" placeholder="Order value (₦)" value={conversion.baseAmount} onChange={e=>setConversion({...conversion,baseAmount:e.target.value})}/><input style={input} placeholder="Admin note" value={conversion.note} onChange={e=>setConversion({...conversion,note:e.target.value})}/><button disabled={busy} onClick={recordConversion} style={{...btn,background:"#07966c",color:"#fff",marginTop:14}}>Create 20% commission</button></div>}
 </main></div>;
}
